# Generated by Django 4.1.1 on 2023-03-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_name', models.CharField(max_length=100)),
                ('Emp_id', models.CharField(max_length=100)),
                ('Emp_phone', models.CharField(max_length=120)),
                ('Emp_address', models.CharField(max_length=100)),
                ('Emp_chackbox', models.BooleanField(default=True)),
                ('Emp_department', models.CharField(max_length=100)),
            ],
        ),
    ]
