# Generated by Django 4.1.1 on 2023-03-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='Emp_address',
            new_name='addres',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='Emp_department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='Emp_id',
            new_name='emp_id',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='Emp_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='Emp_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='Emp_chackbox',
            new_name='working',
        ),
    ]
